baseURL = "https://shouldwehangout.github.io"
title = "Should We Hangout?"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "Should We Hangout?"
  dateFormat = "2017, Sep 13"
  copyrightOwner = "SamNelson"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Minimo"

[author.social]
  codepen = ""
  email = "roadkileggplant@gmail.com"
  facebook = ""
  github = "SamNelson"
  instagram = ""
  twitter = ""
  linkedin = ""

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "ShouldWeHangOut"
  weight = -70
  identifier = "shouldwehangout"
  url = "https://github.com/SamNelson/shouldwehangout.github.io
"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
